# Generated by Django 3.0.5 on 2022-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_link',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
