# Generated by Django 3.0.5 on 2022-10-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_payment_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_link',
            field=models.CharField(default='nil', max_length=255),
        ),
    ]
